### ISSUE TITLE
Error: Cannot find module "entities/maps/entities.json"

### ISSUE THREAD

**Issue by rewmike** [sapegin/react-styleguidist#135]
Latest 2.2.1 release throws error in console: 

    Error: Cannot find module "entities/maps/entities.json"

Release 2.2.0 works fine, related to changes in #131.

I am running Node v5.0.0 and npm v3.3.6.

**Comment by mik01aj** [comment]
My fault (see [this commit](https://github.com/sapegin/react-styleguidist/commit/7e182ba2ae01a9b735e2a6b5163d240f575a96ac)).

But on the other hand, I don't understand why that `/node_modules\/entities\/.*\.json$/` regex doesn't match that JSON module. Maybe we should replace it with `/entities\/maps\/.*\.json$/`?

**Comment by sapegin** [comment]
Works fine for me: Node 5.10.1, npm 3.8.3. Could you try to remove `node_modules` folder and reinstall all dependencies?

**Comment by rewmike** [comment]
Same issue if starting fresh, running on Windows 10.

**Comment by rewmike** [comment]
```
ERROR in ./~/entities/maps/entities.json
Module parse failed: *****\node_modules\entities\maps\entities.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
at Parser.pp.raise (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:920:13)
at Parser.pp.unexpected (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:1483:8)
at Parser.pp.semicolon (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:1462:73)
at Parser.pp.parseExpressionStatement (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:1976:8)
at Parser.pp.parseStatement (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:1754:188)
at Parser.pp.parseBlock (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:1991:21)
at Parser.pp.parseStatement (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:1735:19)
at Parser.pp.parseTopLevel (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:1648:21)
at Parser.parse (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:1616:17)
at Object.parse (*****\node_modules\webpack\node_modules\acorn\dist\acorn.js:882:44)
at Parser.parse (*****\node_modules\webpack\lib\Parser.js:902:15)
at DependenciesBlock.<anonymous> (*****\node_modules\webpack\lib\NormalModule.js:104:16)
at DependenciesBlock.onModuleBuild (*****\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
at nextLoader (*****\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
at *****\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
at Storage.finished (*****\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
@ ./~/markdown-react-js/~/markdown-it/lib/common/entities.js 6:17-55
Child html-webpack-plugin for "index.html":

```

**Comment by mik01aj** [comment]
Hmmm. From https://webpack.github.io/docs/troubleshooting.html#windows-paths:

> ##### Windows paths
>webpack expects absolute paths for many config options. `__dirname + "/app/folder"` is wrong, because windows uses `\` as path separator. This breaks some stuff. Use the correct separators. I.e. `path.resolve(__dirname, "app/folder")` or `path.join(__dirname, "app", "folder")`.

So shall the regex be `new RegExp(path.join('node_modules', 'entities', '.*\\.json$').replace('\\', '\\\\'))`?... Ugly. 😦

**Comment by sapegin** [comment]
Ugly as Windows ;-( Maybe there’s some npm module to do that in cross-platform way?

**Comment by sapegin** [comment]
But they say that `path.join` returns the correct path separator so we don’t need to replace it.

**Comment by sapegin** [comment]
I think we can use `_.escapeRegExp` here.

**Comment by mik01aj** [comment]
or we could use `/[/\\]/` regex to match any path separator.

**Comment by sapegin** [comment]
Could anyone with Windows try this solutions and send a pull request if it works?

**Comment by mdhgriffiths** [comment]
Works for me!

**Comment by tkssharma** [comment]
ERROR in ./~/entities/maps/entities.json
Module parse failed: /Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/entities/maps/entities.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/tarunsharma-xft/UBMAS/ubmas-frontend/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/entities/lib/encode.js 6:32-64

**Comment by tomnattle** [comment]
remove node_modules, run yarn

**Comment by jonathasborges1** [comment]
Remove node_modules e run npm install @angular/cli
