### ISSUE TITLE
Add babel-plugin-react-display-name 

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#18]
To [preserve `displayName`](https://github.com/gaearon/babel-plugin-react-transform#installation) when using `React.createClass()`.

**Comment by mik01aj** [comment]
:+1: This is currently the #1 issue for my styleguide.

**Comment by sapegin** [comment]
Did you try babel-plugin-react-display-name?

**Comment by mik01aj** [comment]
No. I don't really know how and where to add it.

I did some dirty workaround just for me:

![image](https://cloud.githubusercontent.com/assets/3027415/11037711/6c6675cc-86ff-11e5-843b-154efc7e0af7.png)

**Comment by sapegin** [comment]
Looks like I should remove this from the Styleguidist because I have an error:

```
ERROR in ./lib/styleguide/setup.js
Module build failed: ReferenceError: The plugin "react.displayName" collides with another of the same name
    at PluginManager.validate (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/file/plugin-manager.js:159:13)
    at PluginManager.add (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/sapegin/izumi/kao/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/sapegin/izumi/kao/node_modules/babel-loader/index.js:69:12)
 @ multi main

ERROR in ./~/react-styleguidist/src/index.js
Module build failed: ReferenceError: The plugin "react.displayName" collides with another of the same name
    at PluginManager.validate (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/file/plugin-manager.js:159:13)
    at PluginManager.add (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/sapegin/izumi/kao/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/sapegin/izumi/kao/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/sapegin/izumi/kao/node_modules/babel-loader/index.js:69:12)
 @ multi main
```

Looks like we don’t need to require this plugin because it already a dependency of babel-core 5.8 and babel-preset-react (for Babel 6).
