### ISSUE TITLE
Example fails with `config not found`

### ISSUE THREAD

**Issue by operatino** [sapegin/react-styleguidist#35]
```
robert-air:example operatino $ ls
lib                  styleguide.config.js

robert-air:example operatino $ styleguidist build
Building style guide...
/Users/operatino/.nvm/versions/node/v4.2.1/lib/node_modules/react-styleguidist/src/utils/config.js:80
			throw Error('Styleguidist config not found: ' + CONFIG_FILENAME + '.');
			^

Error: Styleguidist config not found: styleguide.config.js.
    at Error (native)
    at findConfig (/Users/operatino/.nvm/versions/node/v4.2.1/lib/node_modules/react-styleguidist/src/utils/config.js:80:10)
    at readConfig (/Users/operatino/.nvm/versions/node/v4.2.1/lib/node_modules/react-styleguidist/src/utils/config.js:28:23)
    at Object.<anonymous> (/Users/operatino/.nvm/versions/node/v4.2.1/lib/node_modules/react-styleguidist/src/utils/config.js:102:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/operatino/.nvm/versions/node/v4.2.1/lib/node_modules/react-styleguidist/src/make-webpack-config.js:9:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by operatino** [comment]
Seems like CLI requires to explicitly define config through `--config`, which is a bit confusing. Making UX a bit better, it's probably better to look for standard config name `styleguide.config.js` in the folder, before failing with error.

**Comment by sapegin** [comment]
Of course it does it. But I don’t understand how you run `styleguidist`. Did you install it globally?

Works fine for me:

```
~/example
❯ npm i -D react react-dom react-styleguidist

~/example
❯ ./node_modules/.bin/styleguidist build
Building style guide...
```

**Comment by operatino** [comment]
I've installed it globally, and run as a CLI.

**Comment by sapegin** [comment]
Never tried that and not sure it works. Actually I don‘t see any reason to do it :-)

**Comment by operatino** [comment]
Strage, because it's described in the documentation of the project https://github.com/sapegin/react-styleguidist#cli-commands-and-options

**Comment by sapegin** [comment]
Right now it says:

```
These commands supposed to be placed in package.json scripts (see Installation section above). If you want to run them from command line do it like this: ./node_modules/.bin/styleguidist.
```

If you see any value in working global installation and can fix it I’ll be happy to merge a PR.
