### ISSUE TITLE
TypeError: Illegal kind "string" for plugin ""

### ISSUE THREAD

**Issue by Pink401k** [sapegin/react-styleguidist#59]
Getting the title'd error why trying to run styleguidist.

I'm not sure what's going on.  I tried to troubleshoot myself, but was unsuccessful.

```
> project@1.0.0 styleguide-server /PROJECT
> styleguidist server

Listening at http://localhost:3000

webpack built 25ce954cda50e939fb85 in 823ms
Hash: 25ce954cda50e939fb85
Version: webpack 1.12.2
Time: 823ms
          Asset     Size  Chunks       Chunk Names
build/bundle.js  45.1 kB       0       main
chunk    {0} build/bundle.js (main) 7.69 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] (webpack)-hot-middleware/client.js 3.27 kB {0} [built]
    [2] (webpack)/buildin/module.js 251 bytes {0} [built]
    [3] (webpack)-hot-middleware/~/strip-ansi/index.js 161 bytes {0} [built]
    [4] (webpack)-hot-middleware/~/strip-ansi/~/ansi-regex/index.js 145 bytes {0} [built]
    [5] (webpack)-hot-middleware/client-overlay.js 883 bytes {0} [built]
    [6] (webpack)-hot-middleware/process-update.js 2.93 kB {0} [built]

ERROR in ./~/react-styleguidist/src/index.js
Module build failed: TypeError: Illegal kind "string" for plugin ""
    at PluginManager.add (/PROJECT/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/plugin-manager.js:196:13)
    at File.buildTransformers (/PROJECT/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/PROJECT/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/PROJECT/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/PROJECT/node_modules/react-styleguidist/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/PROJECT/node_modules/react-styleguidist/node_modules/babel-loader/index.js:71:12)
 @ multi main
```

**Comment by zachkadish** [comment]
same issue here

**Comment by mik01aj** [comment]
I just upgraded from `1.2.1` to `1.3.0` and can reproduce the problem.

**Comment by mik01aj** [comment]
The bug is in https://github.com/sapegin/react-styleguidist/blob/c3b030083c9a0cb4f911d32d27e65184ba2b6d5a/src/make-webpack-config.js#L153 - reactTransformPath is `""`.

**Comment by mik01aj** [comment]
And this is probably because `process.cwd()` is not the folder of `react-styleguidist`, but the folder of the project that is using it. `getInstalledPath` expects the library to be installed in `${process.cwd()}/node_modules/babel-plugin-react-transform` and this is not true with npm 2.x.

@sapegin could you fix it?

**Comment by mik01aj** [comment]
@sapegin we could use [`require.resolve(...)`](https://nodejs.org/api/modules.html) instead of `get-installed-path`.

**Comment by sapegin** [comment]
@mik01aj Thanks for the investigation, I’ll try it soon.

**Comment by mik01aj** [comment]
@sapegin will you fix it or shall I try? This issue hits anyone using npm 2.x (so, most of devs imho)

**Comment by sapegin** [comment]
It’d be cool if you try.

**Comment by mik01aj** [comment]
Turns out I can't today, sorry. Maybe tomorrow... :(

**Comment by mik01aj** [comment]
@sapegin, please have a look at the PR :)

**Comment by mik01aj** [comment]
@Pink401k and @zachkadish, we fixed this, please check if `1.3.1` works for you.

**Comment by subsumo** [comment]
I'm getting it on a fresh install; 
![screen shot 2015-12-16 at 10 03 34 am](https://cloud.githubusercontent.com/assets/164204/11844336/4cd760fa-a3dc-11e5-9ae8-4f29bb32d53a.png)

**Comment by Pink401k** [comment]
That seems to have done it! Thank you.
