### ISSUE TITLE
Trying styleguidust out on an existing project

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#9]
Hi, first I wanted to say that your project looks impressive! :)

But I just tried styleguidist on my existing project, and it failed with a lot of errors. From what I understand, `react-styleguidist/loaders/props.loader.js` tried to parse my `*.jsx` files as ordinary JS (error message is mostly `Unexpected token <`). I don't know why exactly this happens, but it seems to me that styleguidist has some assumptions about project that aren't mentioned in the readme. I'll try to list what might be relevant here (i.e. how my project differs from your example):

* I use `.jsx` file extension, the example uses `.js`.
* I don't use webpack, I use browserify with babel transform.
* I don't use ES6 modules, I use the oldschool `require()` and `module.exports`.
* I use the `ui/**/*.jsx` path for my components, and this path includes unit tests as well. (I use the [Jest's recommended directory structure](http://facebook.github.io/jest/docs/getting-started.html)).

Any suggestions what I could do to make it work?

--- 

P.S. I just tried `react-docgen` CLI on some example component of mine and it works fine.

**Comment by mik01aj** [comment]
I managed to get rid of errors with my files with this config:

```js
module.exports = {
    rootDir: './app',
    components: './scripts/ui/[ABCDEFGH]*.jsx', // Using just some of the components
    updateWebpackConfig: function (webpackConfig) {
        webpackConfig.module.loaders[0].test = /\.jsx?$/;
        webpackConfig.resolve.extensions = ['', '.js', '.jsx', '.json'];
        console.log('webpackConfig', JSON.stringify(webpackConfig, null, 4));
        return webpackConfig;
    },
};
```

But it still fails with this error:

```
ERROR in ./~/react-styleguidist/src/components/StyleGuide/StyleGuide.js
Module build failed: SyntaxError: ......./node_modules/react-styleguidist/src/components/StyleGuide/StyleGuide.js: Unexpected token (7:18)
   5 |
   6 | export default class StyleGuide extends Component {
>  7 | 	static propTypes = {
     |                   ^
   8 | 		title: PropTypes.string.isRequired,
   9 | 		components: PropTypes.array.isRequired
  10 | 	}
    at Parser.pp.raise (......./node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (......./node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseClassProperty (......./node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:624:61)
    at Parser.parseClassProperty (......./node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:797:20)
    at Parser.pp.parseClass (......./node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:567:32)
    at Parser.pp.parseExprAtom (......./node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:405:19)
    at Parser.parseExprAtom (......./node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (......./node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (......./node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (......./node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (......./node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (......./node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExport (......./node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:682:21)
    at Parser.parseExport (......./node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:679:20)
    at Parser.pp.parseStatement (......./node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:115:90)
    at Parser.parseStatement (......./node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:621:22)
 @ ./~/react-styleguidist/src/components/StyleGuide/index.js 9:20-46
```

**Comment by sapegin** [comment]
I’ll add .jsx support but the last error is strange. Looks like Babel ignored settings in `.babelrc`. Would you mind sending me your code at artem@sapegin.ru so I can debug?

**Comment by reintroducing** [comment]
I actually got to this point as well after adding the jsx loader in my config and after seeing this I gave up yesterday :)  I'll be watching this issue closely.

**Comment by sapegin** [comment]
Please try 0.1.5.

**Comment by reintroducing** [comment]
Just tried it and got the following:

```
Listening at http://localhost:3000

webpack built eed122f68a8203cb121f in 619ms
Hash: eed122f68a8203cb121f
Version: webpack 1.12.2
Time: 619ms
          Asset     Size  Chunks       Chunk Names
build/bundle.js  21.3 kB       0       main
chunk    {0} build/bundle.js (main) 40 bytes [rendered]
    [0] multi main 40 bytes {0} [built] [2 errors]

ERROR in ./~/react-styleguidist/~/webpack-hot-middleware/client.js
Module build failed: ReferenceError: Unknown plugin "react-transform"
    at PluginManager.subnormaliseString (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/index.js:69:12)
 @ multi main

ERROR in ./~/react-styleguidist/src/index.js
Module build failed: ReferenceError: Unknown plugin "react-transform"
    at PluginManager.subnormaliseString (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/index.js:69:12)
 @ multi main
```

**Comment by sapegin** [comment]
At least is’s something new ;-) I can reproduce it, so I’ll try to fix it soon.

**Comment by sapegin** [comment]
Should work in 0.1.7.

**Comment by reintroducing** [comment]
Just tried it. New error :)

```
ERROR in ./~/react-styleguidist/~/css-loader!./~/react-styleguidist/~/style-loader!./~/react-styleguidist/~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/react-styleguidist/~/postcss-loader!./~/react-styleguidist/~/react-codemirror/~/codemirror/lib/codemirror.css
Module build failed: CssSyntaxError: /Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/style-loader/index.js!/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/postcss-loader/index.js!/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/react-codemirror/node_modules/codemirror/lib/codemirror.css:1:4: Unknown word
    at Input.error (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/input.js:61:21)
    at Parser.unknownDecl (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parser.js:470:26)
    at Parser.decl (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parser.js:227:22)
    at Parser.word (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parser.js:135:30)
    at Parser.loop (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parser.js:60:26)
    at parse (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parse.js:25:12)
    at new LazyResult (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/lib/processCss.js:165:11)
    at Object.module.exports (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/lib/loader.js:22:2)
 @ ./~/react-styleguidist/~/react-codemirror/~/codemirror/lib/codemirror.css 4:14-258 13:2-17:4 14:20-264

ERROR in ./~/react-styleguidist/~/css-loader!./~/react-styleguidist/~/style-loader!./~/react-styleguidist/~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/react-styleguidist/~/postcss-loader!./~/react-styleguidist/~/react-codemirror/~/codemirror/theme/base16-light.css
Module build failed: CssSyntaxError: /Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/style-loader/index.js!/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/postcss-loader/index.js!/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/react-codemirror/node_modules/codemirror/theme/base16-light.css:1:4: Unknown word
    at Input.error (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/input.js:61:21)
    at Parser.unknownDecl (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parser.js:470:26)
    at Parser.decl (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parser.js:227:22)
    at Parser.word (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parser.js:135:30)
    at Parser.loop (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parser.js:60:26)
    at parse (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/parse.js:25:12)
    at new LazyResult (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/lib/processCss.js:165:11)
    at Object.module.exports (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/css-loader/lib/loader.js:22:2)
 @ ./~/react-styleguidist/~/react-codemirror/~/codemirror/theme/base16-light.css 4:14-260 13:2-17:4 14:20-266
```

Also of note is I'm seeing this when first running it:

```
> styleguidist server

Listening at http://localhost:3000

[BABEL] Note: The code generator has deoptimised the styling of "/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/lodash/index.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/index.js?stage=0!/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/lodash/index.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/react-codemirror/node_modules/codemirror/lib/codemirror.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/index.js?stage=0!/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/react-codemirror/node_modules/codemirror/lib/codemirror.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/babel-loader/index.js?stage=0!/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/react-styleguidist/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js" as it exceeds the max of "100KB".
webpack built abe218ecd1c297e3027e in 28904ms
Hash: abe218ecd1c297e3027e
Version: webpack 1.12.2
Time: 28904ms
```

**Comment by sapegin** [comment]
I had both of them before 0.1.7. Try to reinstall the dependencies: 

```
rm -rf node_modules
npm install
```

If it doesn’t help I’ll need some code to debug because I can’t reproduce these errors anymore.

**Comment by reintroducing** [comment]
Here you go: http://dev.reintroducing.com/2014/stylist.zip

This is as small as possibly I could make the project so its easy to share and still shows the errors I'm experiencing.  Let me know if you need anything else.

**Comment by sapegin** [comment]
Works with this config:

```
module.exports = {
    title: 'React Components',
    rootDir: './frontend',
    components: 'src/js/components/icon/*.jsx',
    styleguideDir: './docs-react'
};
```

rootDir shoudn’t point to the project root with node_modules etc. It drives Webpack mad when it tries to compile stuff inside node_modules. I should clarify in the docs and improve config validation.

**Comment by reintroducing** [comment]
Well that's completely embarassing :)  Thanks alot, this is now working great, really appreciate all the help.  Keep up the great work.

**Comment by sapegin** [comment]
I’m glad to hear it ;-)

**Comment by mik01aj** [comment]
@sapegin, thanks for your work! I can now run styleguidist, and it can display the props for one component, but when I add another one, it fails:

![image](https://cloud.githubusercontent.com/assets/3027415/10279275/92bb7de6-6b64-11e5-8d1a-002fc7921aee.png)

Here are the `propTypes` of the relevant component:

```
    propTypes: {
        issue: React.PropTypes.object,
        width: React.PropTypes.oneOf([26, 40, 55, 70, 110, 155, 190, 265]),
        style: React.PropTypes.object,
    },
```

**Comment by sapegin** [comment]
@mik01aj could you please move this to a new issue? I’ll look at it.
