### ISSUE TITLE
Unable to run customised example

### ISSUE THREAD

**Issue by vyorkin** [sapegin/react-styleguidist#94]
Module build failed: TypeError: Cannot read property 'sync' of undefined

```
 [611] ./~/css-loader?modules&importLoaders=1&localIdentName=ReactStyleguidist-[name]__[local]!./src/styles.css 196 bytes {0} [built]

ERROR in ./loaders/styleguide.loader.js!
Module build failed: TypeError: Cannot read property 'sync' of undefined
    at Object.module.exports.components (/Users/vyorkin/projects/github/react-styleguidist/examples/customised/styleguide.config.js:7:14)
    at Object.module.exports.pitch (/Users/vyorkin/projects/github/react-styleguidist/loaders/styleguide.loader.js:40:29)
 @ ./src/index.js 31:15-37
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.12 MB       0
    chunk    {0} index.html 412 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/templates/index.html 411 bytes {0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/index.js 411 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
```

**Comment by mik01aj** [comment]
Could you share your config? What versions of webpack (and loaders) do you use?

**Comment by vyorkin** [comment]
I've just cloned the repo and ran `npm install && run start:customised`

**Comment by oliverturner** [comment]
I'll take a look

**Comment by sapegin** [comment]
Didn’t check but should work ;-)

**Comment by oliverturner** [comment]
Just checked with a fresh install: works for me

**Comment by vyorkin** [comment]
yes, it works :+1: thank you
