### ISSUE TITLE
Module build failed when starting styleguidist server 

### ISSUE THREAD

**Issue by hokuma** [sapegin/react-styleguidist#99]
This is a project where error happens.
https://github.com/hokuma/sample-styleguide

Mac OX El Capitan 10.11.3
node: 4.2.4
npm: 2.14.12

```
$ npm run styleguide-server

....

ERROR in ./~/react-styleguidist/~/markdown-react-js/lib/index.js
Module build failed: ReferenceError: [BABEL] /Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/markdown-react-js/lib/index.js: Unknown option: /Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/markdown-react-js/.babelrc.stage
    at Logger.error (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:18)
    at OptionManager.addConfig (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:10)
    at OptionManager.findConfigs (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/options/option-manager.js:434:16)
    at OptionManager.init (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/options/option-manager.js:489:12)
    at File.initOptions (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/index.js:211:75)
    at new File (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/file/index.js:129:22)
    at Pipeline.transform (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
    at transpile (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/ohkuma/workspace/sample-styleguide/node_modules/react-styleguidist/node_modules/babel-loader/index.js:88:12)
```

**Comment by sapegin** [comment]
It says unknown option `stage`. Which Babel version do you use?

**Comment by hokuma** [comment]
I am using v6.6.4.

```
$ ./node_modules/.bin/babel --version
6.6.4 (babel-core 6.6.4)
```

**Comment by sapegin** [comment]
For Babel 6 [you need to use presets](https://medium.com/@malyw/how-to-update-babel-5-x-6-x-d828c230ec53#.phkaxw7t8).

**Comment by hokuma** [comment]
I have already used presets, but I have resolved this problem by excluding project dependent node_modules from module.loaders.

IMHO:
`react-styleguidist` itself is dependent on `markdown-react-js' which works for babel5. When staring styleguidist server, babel6 tries to process `markdown-react-js` in node_modules and fails.

Thanks.

```
updateWebpackConfig: function(webpackConfig, env) {
    webpackConfig.module.loaders.push(
      {
        test: /\.js$/,
        // Affect only your project’s files
        include: __dirname,
        exclude: /node_modules/,
        // Babel loader will use your project’s .babelrc
        loader: 'babel'
      }
    );
    return webpackConfig;
  }
```

**Comment by oliverturner** [comment]
can you post your `.babelrc`?

**Comment by sapegin** [comment]
If you use `include` you won't need `exclude`. Why it tries to read anything in `node_modules`?

**Comment by sapegin** [comment]
It doesn’t matter which version of Babel `markdown-react-js` uses because styleguidist uses transpiled files. But they shouldn’t publish `.babelrc` to npm I think.

**Comment by mik01aj** [comment]
@sapegin I can't see why it would be invalid to use both `include` and `exclude`. See [the webpack docs](https://webpack.github.io/docs/configuration.html#module-loaders). I usually use `exclude:  /node_modules/,` to exclude all the not-my-project code.

**Comment by sapegin** [comment]
It’s valid but not very useful. But `include: __dirname` in readme is a mistake, I’ll fix it ;-) It should be `'src/' + __dirname`

**Comment by mik01aj** [comment]
and what if I have toplevel files? `exclude: /node_modules/` is more robust imho.

**Comment by oliverturner** [comment]
@mik01aj it's more robust because it's a looser definition of what to include. `include` reduces the surface area of what's being parsed and is therefore a more accurate implementation of your intent.

**Comment by sapegin** [comment]
Yeah, `include` is more explicit.

**Comment by hokuma** [comment]
@oliverturner 
This is my .babelrc. 

```
{
  'presets': ['es2015', 'react', 'stage-0']
}
```

@sapegin 
Change my webpack config following this comitt(9569354), and it works. 

Thanks!
